config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  root 'pages#index'
  get 'follow/:id' => 'relationships#follow', as: 'follow'
  get 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get  'search', to: 'microposts#search'
  resources :pages
  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :postcomments, only: [:create]
  end
  resources :notifications, only: [:index, :destroy]


=======
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
>>>>>>> origin/master
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  has_many :postcomments
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  has_many :notifications, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader
  validates :user_id, presence: true
  validates :comment, length: { maximum: 2200 }
  validates :image,   presence: true

  #検索にて、投稿内容と完全一致するものを表示
  def self.search(search)
    return Micropost.all unless search
    Micropost.where(['comment LIKE ?', "%#{search}%"])
  end

  #いいねの通知
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(
      micropost_id: id,
      visited_id: user_id,
      action: "like"
    )
    notification.save if notification.valid?
  end

  #コメントの通知
  def create_notification_postcomment!(current_user, postcomment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Postcomment.select(:user_id).where(micropost_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
        save_notification_comment!(current_user, postcomment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, postcomment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, postcomment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      micropost_id: id,
      postcomment_id: postcomment_id,
      visited_id: visited_id,
      action: 'postcomment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :sign_in_required


 def new
   @user = User.find(current_user.id)
   @micropost = @user.microposts.build
   @micropost.image = "micropost.jpg"
 end

 def show
   @micropost = Micropost.find_by(id:params[:id])
   @like = Like.new
   @postcomments = @micropost.postcomments
   @postcomment = @micropost.postcomments.build
 end


 def create
   @micropost = current_user.microposts.build(micropost_params)
   if @micropost.save
     flash[:notice] = "投稿しました"
     redirect_to page_path(current_user)
   else
     render 'microposts/new'
   end
 end

 def destroy
 end

 def search
    #Viewのformで取得したパラメータをモデルに渡す
    @search_posts = Micropost.search(params[:search])
 end


 private
  def micropost_params
   params.require(:micropost).permit(:comment, :image)
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<div class="d-flex justify-content-center">
  <div class="card w-50 mb-5">
    <div class="card-body">
      <% if micropost.user.avatar? %>
        <img src='<%= micropost.user.avatar %>'
             class ="micropost_pages_icon_image d-inline-block"
             alt = "ユーザーアイコン">
      <% else %>
        <img src="/assets/default.jpg"
             class = "micropost_pages_icon_image d-inline-block"
             alt = "ユーザーアイコン" %>
      <% end %>
      <p class="card-text d-inline-block">
        <%= link_to micropost.user.user_name, page_path(micropost.user) %>
      </p>
    </div>
    <div class="w-100 d-flex justify-content-center">
      <%= link_to image_tag(micropost.image.to_s,
                            class: "micropost-image-size"),
                            micropost_path(micropost.id) %>
    </div>
    <div class="card-body">
      <p class="card-text d-block">
        <%= micropost.comment %>
      </p>
      <span class="card-text">
        <%= time_ago_in_words(micropost.created_at) %>前
      </span>
    </div>
  </div>
</div>

app/views/microposts/new.html.erb
<% provide(:title,"写真投稿") %>
<div class="d-flex justify-content-center">
  <%= form_with model: @micropost do |f| %>

    <div class="field">
      <%= f.label :投稿写真 %><br />
      <%= f.file_field :image,
                        id: "micropost_img",
                        class: "image",
                        accept: "image/jpeg,image/png" %>
    </div>

    <% if @micropost.image.present? %>
      <div class="micropost_new_preview_size">
        <%= image_tag @micropost, id: :img_prev, class: "micropost_new_size" %>
      </div>
    <% else %>
      <div class="micropost_new_preview_size">
        <img src="/assets/micropost.jpg"
             id="img_prev"
             class="micropost_new_size"
             alt = "#" %>
      </div>
    <% end %>

    <script type="text/javascript">
      $(function() {
        function readURL(input) {
            if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
        $('#img_prev').attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
            }
        }
        $("#micropost_img").change(function(){
            readURL(this);
        });
      });
    </script>

    <div class="field">
      <%= f.label :コメント %><br />
      <%= f.text_area :comment %>
    </div>

    <div class="actions">
      <%= f.submit "投稿"%>
    </div>

  <% end %>
</div>

app/views/microposts/search.html.erb
<% provide(:title,"検索結果") %>
<% @search_posts.each do |post| %>
  <%= render post %>
<% end %>

app/views/microposts/show.html.erb
<% provide(:title,"投稿詳細") %>
<div class="d-flex justify-content-center">
  <div class="card w-50 mb-5">
    <div class="card-body">
      <% if @micropost.user.avatar? %>
        <img src='<%= @micropost.user.avatar %>'
             class ="micropost_pages_icon_image d-inline-block"
             alt = "ユーザーアイコン">
      <% else %>
        <img src="/assets/default.jpg"
             class = "micropost_pages_icon_image d-inline-block"
             alt = "ユーザーアイコン" %>
      <% end %>
      <p class="card-text d-inline-block">
        <%= link_to @micropost.user.user_name, page_path(@micropost.user) %>
      </p>
    </div>
    <div class="w-100 d-flex justify-content-center">
      <%= link_to image_tag(@micropost.image.to_s,
          class: "micropost-image-size"), micropost_path(@micropost.id) %>
    </div>
    <div class="card-body">
      <p class="card-text d-block m-2">
        <%= simple_format(@micropost.comment) %>
      </p>
      <span class="card-text m-2">
        <%= time_ago_in_words(@micropost.created_at) %>前
      </span>
    </div>
    <div class="card-footer">
      <div class="p-2">
        <h4>いいね件数: <%= @micropost.likes.count %></h4>
        <% if current_user.already_liked?(@micropost) %>
          <%= button_to 'いいねを取り消す',
                        micropost_like_path(@micropost), method: :delete %>
        <% else %>
          <%= button_to 'いいね', micropost_likes_path(@micropost) %>
        <% end %>
      </div>
      <div class="p-2">
        <p>コメント一覧</p>
        <% @postcomments.each do |c| %>
          <div class="py-3 px-5">
            <% unless c.user.blank? %>
              <div class="d-inline-block d-flex align-items-start w-30">
                <a href="<%= page_path(c.user_id) %>" >
                  <% if c.user.avatar? %>
                    <%= image_tag c.user.avatar.to_s,
                    class:"micropost_comment_pages_icon_image mr-3 mb-3"%>
                  <% else %>
                    <%= image_tag "/assets/default.jpg",
                        class:"micropost_comment_pages_icon_image mr-3 mb-3" %>
                  <% end %>
                </a>
                <%= c.user.user_name unless c.user.blank? %>
                <div class="d-inline-block pl-5">
                  <%= simple_format(c.content) %>
                  <p class="microposts_time_ago">
                    <%= time_ago_in_words(c.created_at) %>前
                  </p>
                </div>
              </div>
            <% end %>
          </div>
          <br />
        <% end %>
      </div>
      <% if user_signed_in? %>
        <%= form_with(model: [@micropost, @postcomment], local: true) do |f| %>
          <%= f.text_area :content, class: "form-control", rows: 5 %>
          <%= button_tag type: "submit",
                         class: "btn btn-success float-right mt-1" do %>
            <i class="far fa-comments"></i> コメントする
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>