config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  devise_scope :user do
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  root 'pages#index'
  get 'follow/:id' => 'relationships#follow', as: 'follow'
  get 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get  'search', to: 'microposts#search'
  resources :pages
  resources :microposts, only: [:new, :show, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
    resources :postcomments, only: [:create]
  end
  resources :notifications, only: [:index, :destroy]


=======
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
>>>>>>> origin/master
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<<<<<<< HEAD
    <%= favicon_link_tag 'favicon.ico' %>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/64a2167754.js" crossorigin="anonymous"></script>

  </head>

  <body>
    <header>
      <div class="header-size">
        <nav class = "content-center navbar" >
          <%= form_tag(search_path,:method => 'get') do %>
            <%= text_field_tag :search %>
            <%= submit_tag '検索', :comment => nil %>
          <% end %>
            <% if user_signed_in? %>
              <%= link_to page_path(current_user.id) do %>
                <i class="fas fa-user fa-lg black"></i>
              <% end %>
              <%= link_to new_micropost_path do %>
                <i class="far fa-plus-square fa-lg black"></i>
              <% end %>
              <%= link_to root_path do %>
                <i class="fas fa-house-user fa-lg black"></i>
              <% end %>
              <% if unchecked_notifications.any? %>
                <%= link_to notifications_path do %>
                    <i class = "fas fa-bell fa-lg "></i>
                <% end %>
              <% else %>
                <%= link_to notifications_path do %>
                    <i class = "fas fa-bell fa-lg black"></i>
                <% end %>
              <% end %>

            <% else %>
              <%= link_to '新規ユーザー登録', new_user_registration_path %>
              <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
        </nav>
      </div>
    </header>
    <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="blank_space">
    </div>

    <%= yield %>

    <div class="blank_space">
    </div>
=======
    <title>SubTaskApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
>>>>>>> origin/master
  </body>
</html>